dist: trusty

language: python
python:
  - "3.5"

before_install:
  - apt-get install -y liblas-c3 libopenblas-base

install:
  - pip install -e .
  - pip install pytest pytest-benchmark

addons:
  apt:
    update: true

jobs:
  include:
    - stage: tests
      if: branch = Tiler
      script:
      - |
        pytest
        py3dtiles info tests/pointCloudRGB.pnts
