sudo: required
dist: bionic

addons:
  postgresql: "12"
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-2.5

jobs:
  include:
    - stage: tests
      language: python
      python: "3.6"
      install:
          ### Dealing with py3dtiles sub-dependencies
        - sudo add-apt-repository universe
        - sudo apt-get install -y liblas-c3 libopenblas-base flake8
          ### Proceed with the install of py3dtilers per se.
          # The extra flag installs the dev dependencies, refer to e.g.
          # https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
        - pip install -e .[dev]
        - python -c 'import ifcopenshell'  # Just to make sure
      script:
      - |
        autopep8 --in-place --recursive py3dtilers/
        pytest --flake8
        pytest -v
    - stage: "Markdown link checks"
      language: node_js
      node_js: 12
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi


