sudo: required
dist: bionic

language: python
python:
  - "3.6"

install:
  - pip install -e . -v
  - pip install pytest pytest-benchmark

addons:
  apt:
    update: true

jobs:
  include:
    - stage: tests
      script:
      - |
        pytest
        py3dtiles info tests/pointCloudRGB.pnts
