sudo: required
dist: bionic

addons:
  postgresql: "9.4"
  apt:
    update: true
    packages:
      - postgresql-9.4-postgis-2.4

jobs:
  include:
    - stage: tests
      language: python
      python: "3.6"
      install:
          ### Dealing with py3dtiles sub-dependencies
        - sudo add-apt-repository universe
        - sudo apt-get install -y liblas-c3 libopenblas-base flake8
          ### Proceed with the install of py3dtilers per se.
          # The extra flag installs the dev dependencies, refer to e.g.
          # https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
        - pip install -e .[extra]
        - python -c 'import ifcopenshell'  # Just to make sure
      before_script:
        - psql -c 'create database test_tiler;' -U postgres
        - psql -U postgres -d test_tiler < tests/city_tiler_test_data/buildings.sql
      script:
      - |
        pytest
        pytest -v
    - stage: "Markdown link checks"
      language: node_js
      node_js: 12
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=4
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi


