sudo: required
dist: bionic

language: python
python:
  - "3.6"

install:
    ### Dealing with py3dtiles sub-dependencies
  - sudo add-apt-repository universe
  - sudo apt-get install -y liblas-c3 libopenblas-base flake8
    ### Proceed with the install of py3dtilers per se.
    # The extra flag installs the dev dependencies, refer to e.g.
    # https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
  - pip install -e .[extra] -v  # 

addons:
  apt:
    update: true

jobs:
  include:
    - stage: tests
      script:
      - |
        pytest
        py3dtiles info tests/pointCloudRGB.pnts
